name: tools
channels:
  - conda-forge
  - bioconda
dependencies:
  - samtools
  - bcftools
  - pbmm2
  - pbsv
  - sniffles
  - hiphase
  - pb-cpg-tools
  - minimod
  - survivor
  - glnexus
platforms:
  - linux-64